#!/bin/bash

echo "DONE"

REL_PATH=$1
CONFIG_NAME=$2
HOST_NAME=$3


cp $1si5344_config/$2 $1/Flash_Firmware/Si5344_REG_PLL.h

# echo "rsync -ra "$1"Flash_Firmware" $3:
rsync -ra $1Flash_Firmware $HOST_NAME:


#Compile and Run

ssh -T $HOST_NAME << EOF
  cd Flash_Firmware

  echo "We are in dir::\$PWD"
  ./compile.sh
  sudo ./loc_pll.exe 
  sudo ./mezz_pll.exe
EOF